### ISSUE TITLE
The download of source data

### ISSUE THREAD

**Issue by Solacex** [VisionLearningGroup/visda21-dev#1]
Hello, 

I want to make sure that if there is any difference between the imagenet from Kaggle and the ILSVRC2012_img_train.tar from the https://image-net.org/download.php. 

Kaggle has explained that its a mirror from image-net.org, but I want to double-check this as they seems are two challenges.

**Comment by samarth4149** [comment]
They should be the same set. Is there a difference in the list of images?

**Comment by Solacex** [comment]
I have downloaded the imagenet from imagenet-net.org but don't have the list from kaggle. could you share the path list with us so we could compare them?

**Comment by Solacex** [comment]
I have found the list from kaggle.

**Comment by Solacex** [comment]
Hello, I have checked them, and the two are exactly the same.

**Comment by samarth4149** [comment]
Thanks for checking. Somehow got no notifications from your responses 3 days ago.
