### ISSUE TITLE
Submission format

### ISSUE THREAD

**Issue by cuishuhao** [VisionLearningGroup/visda21-dev#4]
Hello,
I try to direct upload the "source_only_pred.txt" to the website, but get "Invalid file type (text/plain).".
I also try to zip "source_only_pred.txt"  and "adapt_pred.txt", and upload the zip file.
They both fail, and I wonder the submission format.
Thank you!

**Comment by MInner** [comment]
This page https://competitions.codalab.org/competitions/33396#learn_the_details-evaluation has a link to an example submission file. It is a zip with two text files. When the submission fails, you can often check the status / error message.

**Comment by cuishuhao** [comment]
Hello, 
I run the , and get demo.zip https://drive.google.com/file/d/1gbrAtjKqtO5q27Y26lvAdUo5dQSmA4GC/view?usp=sharing. However, I got the following error “
Exception: Submitted files do not correpond to GT files!”, when submitting the file to the website. I wonder why.
Thank you!

**Comment by MInner** [comment]
Sorry for a late response, @cuishuhao ! Judging from the leaderboard, you managed to get it working. Do you mind sharing what was the issue?

**Comment by cuishuhao** [comment]
@MInner Sorry, I still face the problem. I can only upload the demo files. Could you help me figure out the problem?

**Comment by MInner** [comment]
Could you please send me your submission to usmn at bu dot edu so I can take a closer look?

**Comment by cuishuhao** [comment]
Hello, my submission file is https://drive.google.com/file/d/1gbrAtjKqtO5q27Y26lvAdUo5dQSmA4GC/view?usp=sharing.
![image](https://user-images.githubusercontent.com/9152900/130163746-91466eda-6b1e-40c2-b86f-3a4780ee3b84.png)

**Comment by MInner** [comment]
This (`demo.zip`) file gets successfully evaluated when I submit it. Moreover, it has the exact same files as the example submission we provided.
 
```
$ md5sum */*.txt
c272ebb623c070d9ef4bad6809d29b52  demo/adapt_pred.txt
c272ebb623c070d9ef4bad6809d29b52  demo/source_only_pred.txt
c272ebb623c070d9ef4bad6809d29b52  same/adapt_pred.txt
c272ebb623c070d9ef4bad6809d29b52  same/source_only_pred.txt
```


Are you sure that this is the correct file?

**Comment by MInner** [comment]
In general, make sure that your prediction file has the same filenames in the same order as the example submission we provide.

**Comment by cuishuhao** [comment]
Thank you!
I find the mistake.
The order of objectnet and imagenet_c_and_r  should be changed similar to demo files.
The demo codes confuse the order.
