### ISSUE TITLE
Doubts about data augmentation

### ISSUE THREAD

**Issue by silvia1993** [VisionLearningGroup/visda21-dev#7]
Hi,

I have two doubts:

1 - Is it allowed to use pixel-level adaptation strategies as style-transfer?
2 - Is standard color jittering (which includes brightness and contrast transformations) forbidden?

Thank you

**Comment by samarth4149** [comment]
Hi,

Sorry about the delay! Here are the answers:

1. Yes, it is allowed to use pixel level adaptation strategies like style transfer.
2. That's correct, using brightness and contrast transformations is not allowed. Any transformations not on the [blacklist](https://github.com/VisionLearningGroup/visda21-dev/blob/main/README.md#corruption-blacklist) are allowed.

**Comment by silvia1993** [comment]
Thank you!
