### ISSUE TITLE
Final deadline

### ISSUE THREAD

**Issue by FrancescoCappio** [VisionLearningGroup/visda21-dev#8]
Hello!
On codalab the final deadline for submission is "Oct. 10, 2021, 5 a.m. UTC", while on the official challenge site it is written "Oct 10th, 11:59 am EST". So which is the correct one?

**Comment by samarth4149** [comment]
Hi,

Sorry about the confusion. It is the latter Oct 10th, 11.59 a.m. EST or Oct 10th, 3.59 p.m. UTC.
