### ISSUE TITLE
Number of submissions allowed

### ISSUE THREAD

**Issue by silvia1993** [VisionLearningGroup/visda21-dev#9]
Hi,

1. From codalab seems that the maximum number of total submission allowed is 5. But I noticed that some users in the leaderboard have more than 5 entries. Why?

2. The submissions ended with "Failed" status are included in the 5 allowed? Or can I ignore them in the count?

3. Once that the 5 possibilities have been used, is it forbidden to create a new account, right? From the leaderboard, I noticed that some users change their names putting a number at the end of the username. (Example: name, name1, name2 etc. )

Thank you!

**Comment by MInner** [comment]
You are correct, the total number of **successful** submissions is capped at five, and creating multiple accounts is actively prohibited, we will make sure to flag violators after submission closes.

**Comment by samarth4149** [comment]
Just to add to the answer, "failed" submissions do not count towards the limit of 5, but they do count in the number you see on the leaderboard.

**Comment by silvia1993** [comment]
ok, thank you!
